### ISSUE TITLE
Document DatabaseCleaner Examples

### ISSUE THREAD

**Issue by metaskills** [customink/secondbase#11]
I think we can document some simple examples using `SecondBase.on_base { ... }` for test setup/teardown when using database cleaner. https://github.com/DatabaseCleaner/database_cleaner/tree/master/lib/database_cleaner/active_record

**Comment by metaskills** [comment]
cc @sarsena

**Comment by sbrady** [comment]
@metaskills that would be awesome I am using DatabaseCleaner, and https://github.com/grosser/parallel_tests

**Comment by Carlows** [comment]
Any examples on how to do this?

**Comment by metaskills** [comment]
Here is an example I have in a Rails v5.1 app.

```ruby
require 'database_cleaner'
DatabaseCleaner.clean_with :truncation, except: [ActiveRecord::InternalMetadata.table_name]
DatabaseCleaner.clean

require 'factory_girl'
include FactoryGirl::Syntax::Methods
include NamedSeeds::DSL
begin
  FactoryGirl.find_definitions
rescue
  false
end
```

**Comment by metaskills** [comment]
This is at the top of `db/seeds.rb` file
