### ISSUE TITLE
Primary DB Migrations No Longer Work

### ISSUE THREAD

**Issue by jpete7683** [customink/secondbase#25]
When running a normal migration without the secondbase as part of the command no longer update the db/migrate folder.  The command doesn't error out and there is no output to screen but no file is created in the db/migration directory.  Not sure if this is an issue or something that is just undocumented on how to fix.

**Comment by metaskills** [comment]
Not sure I follow. Are you talking about creating a migration like `$ rails g migration FooBar`? That is the only command that would change what is in the db/migrate directory.

**Comment by jpete7683** [comment]
Correct the generic manipulation of the "primary" database.  rails g migration AddColumnToTable does not work.

**Comment by jpete7683** [comment]
So it looks like you were already able to track down this issue and propose a fix.  Should we close or keep it open?

**Comment by metaskills** [comment]
Running tests first.

**Comment by metaskills** [comment]
@jpete7683 Thanks for the issue post. Got it all sorted out in #25 and pushed v1.0.1. Please give it a go and let us know if you have any more issues. Cheers!
