### ISSUE TITLE
Migration generators path not taken care of.

### ISSUE THREAD

**Issue by s-ashwinkumar** [customink/secondbase#3]
The path of the secondary migrations folder has been modified to `db/#{SecondBase::CONNECTION_PREFIX}/#{class_name.underscore}.rb` except for the generator and hence generator still generators migration at `db/migrate/secondbase`

https://github.com/customink/secondbase/blob/rails32_compatible/lib/generators/secondbase/migration_generator.rb#L25

**Comment by metaskills** [comment]
@hmadison Do you want to overhaul the generators for the new 1.0 release? Those are still untested and I think a few things I did will allow them to work better. For example: https://github.com/customink/secondbase/commit/1571b41b94ad6ce46c000ed4ea42b4673311a707
