### ISSUE TITLE
What about ThirdBase?

### ISSUE THREAD

**Issue by stevenharman** [customink/secondbase#41]
I'm not trolling. Really. I have inherited an app which has THREE (3) different DBs. The primary is MySQL. And then there are two different PostreSQL DBs used for metrics and _some-other-thing-I-don't-yet-fully-understand_. The point being, we need to manage 3 different DBs. The current "solution" for that is manually creating various DBs, running migrations for those other DBs from the main migrations, etc... It's a Bad Time™.

I'd like to use SecondBase, but we have that darned ThirdBase too. How tied to only two DBs is this Gem? Would adding support for a third (or arbitrary number, I suppose) be totally absurd?

**Comment by metaskills** [comment]
Love it! We have talked about 3rd base before. Technically we could step and repeat all the things that made this work. I do wonder if you need a true 3rd base tho. Does that "some-other-thing-I-don't-yet-fully-understand" DB require a schema and full participation in the rake tasks? If not, then a good ol' fashion abstract connection class would work. See: https://gist.github.com/metaskills/4065702

If it does need full database task support, then we would have to go with extending SecondBase which may be just fork it and rename everything :)

**Comment by metaskills** [comment]
Wow! Someone did it a few months ago: https://github.com/sagittaros/thirdbase

**Comment by hmadison** [comment]
I ended up prototyping this at one point and pulled back from it. Without some major changes landed in Rails core, you end up having to metaprogram almost everything in the gem to support an n number of databases. This turns into an unintelligible mess very fast, and is impossible to debug.

I feel you have three options here:
* Convert your primary database to postgres then use foreign data wrappers to access the other two databases.  
* Use [Sequel](sequel.jeremyevans.net) over ActiveRecord. Its migration interface is *much* better than activerecord's for managing a large number of databases.
* Clone secondbase and replace second with third everywhere.

**Comment by karledurante** [comment]
You might also want to look into the [Octopus Gem](https://github.com/thiagopradi/octopus).

**Comment by jomei** [comment]
Please, checkout my [solution](https://github.com/jomei/multibase)

**Comment by metaskills** [comment]
@jomei Thanks for posting! I made an issue on your repo to sort out the LICENSE issue. Cheers. https://github.com/jomei/multibase/issues/1

**Comment by shqear93** [comment]
does this feature implemented in secondbase already ?

**Comment by metaskills** [comment]
Oh no... if you need a third, fork and rename :)
