### ISSUE TITLE
SeconBase db:structure:dump

### ISSUE THREAD

**Issue by workgena** [customink/secondbase#50]
I have database. And want to dump current state to `structure.sql`. And there is no task for this.

This task also needed for migrations when set this option:

```ruby
# config/application.rb
config.active_record.schema_format = :sql
```

For this reason I added task:

```rake
namespace :db do
  namespace :second_base do
    namespace :structure do
      task dump: ['db:load_config'] do
        SecondBase.on_base { Rake::Task['db:structure:dump'].execute }
      end
    end
  end
end
```

And it works with
```ruby
config.active_record.dump_schemas = :all
```

But dump is wrong. because of missing :environment task.

This is my fork with fix (no tests): 
https://github.com/workgena/secondbase/blob/master/lib/second_base/databases.rake

**Comment by metaskills** [comment]
Hmm... we also do not have a defined `schema:dump` as well. The idea here is that as other tasks call out to ActiveRecord's task, we have already enabled SecondBase as being `on_base`. I wonder if we should make a `_dump` tasks and that would work for both? https://github.com/rails/rails/blob/master/activerecord/lib/active_record/railties/databases.rake#L64-L77

**Comment by workgena** [comment]
Need to double check this(and write some test, when have some time).

In current protect we prefer to use `config.second_base.run_with_db_tasks = false` and use separate command for migrations. And when run this command `rake db:second_base:migrate` there was two strange mistakes: 
 - first described above (not reading application.rb settings)
 - And the second error: `second_base/structure.sql` somehow contained `INSERT schema_migration...` from first(main) database, but the actually structure of tables was normal for second_database.

When I have some time, I'll do tests fro this cases. And it will be clear what is wrong.

**Comment by metaskills** [comment]
Ah! So yea... I kind of suspect that turning off the task shadowing opens up those issues. In some ways I would like to promote that issues like this can happen and to not use said feature or encourage documented workarounds like yours. 

> When I have some time, I'll do tests fro this cases. And it will be clear what is wrong.

Very cool, appreciate that. I would be open to docs only (maybe #advanced-usage section) PRs too, whatever you find is best. Our tests are pretty easy to clone and run, TravisCI will also run pull requests too. Lastly, we have a little side/demo apps that is fun to play around with for quick integration checks. See here:

* https://github.com/customink/encom_dbs/tree/secondbase-rails42
* https://github.com/customink/encom_dbs/tree/secondbaserails50

Thanks again!
