### ISSUE TITLE
rake tasks for second_base does not load environment

### ISSUE THREAD

**Issue by senid231** [customink/secondbase#59]
ActiveRecord task db:migrate loads environment and config
`activerecord-5.1.4/lib/active_record/railties/databases.rake:56`  
```ruby
desc "Migrate the database (options: VERSION=x, VERBOSE=false, SCOPE=blog)."
task migrate: [:environment, :load_config] do
  ActiveRecord::Tasks::DatabaseTasks.migrate
  db_namespace["_dump"].invoke
end
```

And SecondBase task db:second_base:migrate loads only config
`secondbase-2.1.4/lib/second_base/databases.rake:30`  
```ruby
task :migrate => ['db:load_config'] do
  SecondBase.on_base { Rake::Task['db:migrate'].execute }
end
```

as result I can't you classes/modules from `app` folder in migrations for second database

**Comment by senid231** [comment]
it should be
```
task :migrate => ['db:load_config', :environment] do
  SecondBase.on_base { Rake::Task['db:migrate'].execute }
end
```

**Comment by workgena** [comment]
#50

**Comment by metaskills** [comment]
Can someone open a PR to make that change? Would love to fix this and release a new version.
