### ISSUE TITLE
After Create in Second Base Model

### ISSUE THREAD

**Issue by JonnyGalassi** [customink/secondbase#65]
Hello, I want to alert when add new record in Second Base model, with callback method after_create, but nothing to do. What happend?

**Comment by metaskills** [comment]
Hey @JonnyGalassi thanks for the question. Did you figure this out and/or have you tried to create a simple test case? Off hand I can not think of any reason callbacks would not work, we use Secondbase a lot (with callbacks) and have not seen this. So sharing some code of yours would go a long way in helping.
